# Generated by Django 5.2.8 on 2025-11-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_TODO', '0001_initial'),
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='tasks',
            field=models.ManyToManyField(to='Model_TODO.task'),
        ),
    ]
